// Writes src/config.ts and the network/SSO privileges in capabilities.json for a build.
//
//   npm run configure -- --api https://chatbot-api.contoso.com --app-id-uri https://chatbot-api.contoso.com
//   npm run configure -- --mode dev --api https://localhost:8000          (local development)
//
// The backend URL is fixed at build time on purpose: report authors can't point the visual (and the
// user's token) at another server, and WebAccess only allows the declared origin anyway.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const args = Object.fromEntries(
    process.argv.slice(2).reduce((pairs, arg, i, all) => {
        if (arg.startsWith("--")) pairs.push([arg.slice(2), all[i + 1]]);
        return pairs;
    }, []),
);

const mode = args.mode ?? "entra";
if (!["entra", "dev"].includes(mode)) throw new Error(`--mode must be entra or dev, got ${mode}`);
const api = new URL(args.api ?? "https://chatbot-api.example.com");
if (api.protocol !== "https:") throw new Error("--api must be https:// (Power BI blocks mixed content)");
const appIdUri = args["app-id-uri"] ?? api.origin;

writeFileSync(
    join(root, "src", "config.ts"),
    `// GENERATED by \`npm run configure\` (scripts/configure.mjs) — do not edit by hand.
// Production builds use authMode "entra" (Power BI SSO); "dev" exists only for local development.

export type AuthMode = "entra" | "dev";

export const config: { apiBaseUrl: string; authMode: AuthMode } = {
    apiBaseUrl: ${JSON.stringify(api.origin)},
    authMode: ${JSON.stringify(mode)},
};
`,
);

const capabilitiesPath = join(root, "capabilities.json");
const capabilities = JSON.parse(readFileSync(capabilitiesPath, "utf8"));
capabilities.privileges = [
    { name: "WebAccess", essential: true, parameters: [api.origin] },
    { name: "AADAuthentication", parameters: { COM: appIdUri } },
    { name: "LocalStorage", essential: false },
];
writeFileSync(capabilitiesPath, JSON.stringify(capabilities, null, 4) + "\n");

console.log(`configured: mode=${mode} api=${api.origin} appIdUri=${appIdUri}`);
