"""semantic knowledge: embedding spaces + semantic documents (vectors + full-text)

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-06 18:32:35.433496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_spaces',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embedding_spaces')),
    sa.UniqueConstraint('provider', 'model', name=op.f('uq_embedding_spaces_provider'))
    )
    op.create_table('semantic_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('semantic_model_id', sa.UUID(), nullable=False),
    sa.Column('embedding_space_id', sa.Integer(), nullable=False),
    sa.Column('doc_key', sa.String(length=600), nullable=False),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=600), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('referenced_objects', postgresql.ARRAY(sa.String(length=600)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
    sa.Column('search_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(content, ''))", persisted=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['embedding_space_id'], ['embedding_spaces.id'], name=op.f('fk_semantic_documents_embedding_space_id_embedding_spaces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['semantic_model_id'], ['semantic_models.id'], name=op.f('fk_semantic_documents_semantic_model_id_semantic_models'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semantic_documents')),
    sa.UniqueConstraint('semantic_model_id', 'embedding_space_id', 'doc_key', name=op.f('uq_semantic_documents_semantic_model_id'))
    )
    op.create_index(op.f('ix_semantic_documents_last_seen_at'), 'semantic_documents', ['last_seen_at'], unique=False)
    op.create_index('ix_semantic_documents_model_space', 'semantic_documents', ['semantic_model_id', 'embedding_space_id'], unique=False)
    op.create_index('ix_semantic_documents_search_tsv', 'semantic_documents', ['search_tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_semantic_documents_search_tsv', table_name='semantic_documents', postgresql_using='gin')
    op.drop_index('ix_semantic_documents_model_space', table_name='semantic_documents')
    op.drop_index(op.f('ix_semantic_documents_last_seen_at'), table_name='semantic_documents')
    op.drop_table('semantic_documents')
    op.drop_table('embedding_spaces')
    # ### end Alembic commands ###
