"""core schema: identity, registry, authz cache, metadata, conversations, audit

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-06 17:40:45.632695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.Enum('allow', 'deny', 'success', 'failure', name='audit_outcome', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('entra_tenant_id', sa.String(length=64), nullable=True),
    sa.Column('entra_object_id', sa.String(length=64), nullable=True),
    sa.Column('pbi_dataset_id', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("outcome IN ('allow', 'deny', 'success', 'failure')", name=op.f('ck_audit_events_audit_outcome')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_entra_object_id'), 'audit_events', ['entra_object_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_occurred_at'), 'audit_events', ['occurred_at'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entra_tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('entra_tenant_id', name=op.f('uq_tenants_entra_tenant_id'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entra_tenant_id', sa.String(length=64), nullable=False),
    sa.Column('entra_object_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('entra_tenant_id', 'entra_object_id', name=op.f('uq_users_entra_tenant_id'))
    )
    op.create_index(op.f('ix_users_last_seen_at'), 'users', ['last_seen_at'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('pbi_workspace_id', sa.String(length=64), nullable=False),
    sa.Column('entra_tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces')),
    sa.UniqueConstraint('pbi_workspace_id', name=op.f('uq_workspaces_pbi_workspace_id'))
    )
    op.create_table('semantic_models',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('pbi_dataset_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'disabled', 'sync_error', name='model_status', native_enum=False, create_constraint=False, length=32), server_default='active', nullable=False),
    sa.Column('chatbot_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('schema_version', sa.String(length=128), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'disabled', 'sync_error')", name=op.f('ck_semantic_models_model_status')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_semantic_models_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semantic_models')),
    sa.UniqueConstraint('pbi_dataset_id', name=op.f('uq_semantic_models_pbi_dataset_id'))
    )
    op.create_index(op.f('ix_semantic_models_workspace_id'), 'semantic_models', ['workspace_id'], unique=False)
    op.create_table('business_glossary',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('semantic_model_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.Enum('synonym', 'kpi_definition', 'business_rule', 'example_question', name='glossary_entry_type', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('maps_to', sa.String(length=512), nullable=True),
    sa.Column('created_by', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entry_type IN ('synonym', 'kpi_definition', 'business_rule', 'example_question')", name=op.f('ck_business_glossary_glossary_entry_type')),
    sa.ForeignKeyConstraint(['semantic_model_id'], ['semantic_models.id'], name=op.f('fk_business_glossary_semantic_model_id_semantic_models'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_glossary'))
    )
    op.create_index(op.f('ix_business_glossary_semantic_model_id'), 'business_glossary', ['semantic_model_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('primary_semantic_model_id', sa.UUID(), nullable=True),
    sa.Column('report_hint', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['primary_semantic_model_id'], ['semantic_models.id'], name=op.f('fk_chat_sessions_primary_semantic_model_id_semantic_models'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_sessions'))
    )
    op.create_index(op.f('ix_chat_sessions_last_activity_at'), 'chat_sessions', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('model_metadata',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('semantic_model_id', sa.UUID(), nullable=False),
    sa.Column('schema_version', sa.String(length=128), nullable=False),
    sa.Column('object_type', sa.Enum('table', 'column', 'measure', 'relationship', 'hierarchy', name='metadata_object_type', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=True),
    sa.Column('object_name', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expression', sa.Text(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("object_type IN ('table', 'column', 'measure', 'relationship', 'hierarchy')", name=op.f('ck_model_metadata_metadata_object_type')),
    sa.ForeignKeyConstraint(['semantic_model_id'], ['semantic_models.id'], name=op.f('fk_model_metadata_semantic_model_id_semantic_models'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_metadata')),
    sa.UniqueConstraint('semantic_model_id', 'schema_version', 'object_type', 'table_name', 'object_name', name=op.f('uq_model_metadata_semantic_model_id'), postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_model_metadata_semantic_model_id'), 'model_metadata', ['semantic_model_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('pbi_report_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('semantic_model_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['semantic_model_id'], ['semantic_models.id'], name=op.f('fk_reports_semantic_model_id_semantic_models'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_reports_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports')),
    sa.UniqueConstraint('pbi_report_id', name=op.f('uq_reports_pbi_report_id'))
    )
    op.create_index(op.f('ix_reports_semantic_model_id'), 'reports', ['semantic_model_id'], unique=False)
    op.create_index(op.f('ix_reports_workspace_id'), 'reports', ['workspace_id'], unique=False)
    op.create_table('user_model_access',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('semantic_model_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('allowed', 'denied', 'unknown', 'stale', name='access_status', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('capability', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('allowed', 'denied', 'unknown', 'stale')", name=op.f('ck_user_model_access_access_status')),
    sa.ForeignKeyConstraint(['semantic_model_id'], ['semantic_models.id'], name=op.f('fk_user_model_access_semantic_model_id_semantic_models'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_model_access_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'semantic_model_id', name=op.f('pk_user_model_access'))
    )
    op.create_index(op.f('ix_user_model_access_expires_at'), 'user_model_access', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_model_access_semantic_model_id'), 'user_model_access', ['semantic_model_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='message_role', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('resolved_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant')", name=op.f('ck_chat_messages_message_role')),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('fk_chat_messages_session_id_chat_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index('ix_chat_messages_session_seq', 'chat_messages', ['session_id', 'seq'], unique=False)
    op.create_table('query_executions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('semantic_model_id', sa.UUID(), nullable=True),
    sa.Column('gateway', sa.String(length=32), nullable=False),
    sa.Column('dax', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('succeeded', 'failed', 'denied', 'rejected', name='query_status', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('truncated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('succeeded', 'failed', 'denied', 'rejected')", name=op.f('ck_query_executions_query_status')),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], name=op.f('fk_query_executions_message_id_chat_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['semantic_model_id'], ['semantic_models.id'], name=op.f('fk_query_executions_semantic_model_id_semantic_models'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('fk_query_executions_session_id_chat_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_query_executions'))
    )
    op.create_index(op.f('ix_query_executions_session_id'), 'query_executions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_executions_session_id'), table_name='query_executions')
    op.drop_table('query_executions')
    op.drop_index('ix_chat_messages_session_seq', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_user_model_access_semantic_model_id'), table_name='user_model_access')
    op.drop_index(op.f('ix_user_model_access_expires_at'), table_name='user_model_access')
    op.drop_table('user_model_access')
    op.drop_index(op.f('ix_reports_workspace_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_semantic_model_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_model_metadata_semantic_model_id'), table_name='model_metadata')
    op.drop_table('model_metadata')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_last_activity_at'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_business_glossary_semantic_model_id'), table_name='business_glossary')
    op.drop_table('business_glossary')
    op.drop_index(op.f('ix_semantic_models_workspace_id'), table_name='semantic_models')
    op.drop_table('semantic_models')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_last_seen_at'), table_name='users')
    op.drop_table('users')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_audit_events_occurred_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entra_object_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
