// GENERATED by `npm run configure` (scripts/configure.mjs) — do not edit by hand.
// Production builds use authMode "entra" (Power BI SSO); "dev" exists only for local development.

export type AuthMode = "entra" | "dev";

export const config: { apiBaseUrl: string; authMode: AuthMode; diagnostics: boolean } = {
    apiBaseUrl: "https://localhost:8000",
    authMode: "entra",
    // Phase 2 spike panel (docs/spikes-runbook.md); always false in builds that are shipped.
    diagnostics: true,
};
