// GENERATED by `npm run configure` (scripts/configure.mjs) — do not edit by hand.
// Production builds use authMode "entra" (Power BI SSO); "dev" exists only for local development.

export type AuthMode = "entra" | "dev";

export const config: { apiBaseUrl: string; authMode: AuthMode } = {
    apiBaseUrl: "https://chatbot-api.example.com",
    authMode: "entra",
};
